import os
import pandas as pd
import numpy as np

import doctor

def main():
  os.system('cls' if os.name == 'nt' else 'clear')
  print("\n"*100)
  print("The \033[1m\033[93mDoctor\033[0m was called...\n")

  table = doctor.TabularBuilder(
    test_data()[1],
    column_format=">{\hsize=.2\hsize}X >{\hsize=.8\hsize}X",
    caption="Example table generated by Python",
    short_caption="Shorter caption for TOC",
    label="tabledemo"
  )

  print(table.get_result())
  

if __name__ == "__main__":
  def test_data():
    """
    Example data for steering Doctor development.
    """
    test_data_numbers = pd.DataFrame(
      np.random.randint(0, 100000000, size=(19, 6)),
      columns=["col" + str(i + 1) for i in range(6)]
    )

    test_data_mixed = pd.DataFrame(
      {
        'Numbers': [np.random.randint(0, 100) for i in range (10)],
        'More numbers': [np.random.randint(0, 100) for i in range (10)],
        'Text': "Lorem ipsum dolor sit amet consectetur adipiscing elit Curabitur nec".split(),
        'Mash': [
          "iswdufvbouwesdbnvg",
          "abc",
          "sdvcsdv",
          "sdvdssdvdvvn",
          "yumyumyum",
          "wqoe",
          "qphjpgh",
          "owperjgpowegjwjggg",
          "wepogjwpeog",
          "oi"
        ]
      }
    )

    return test_data_numbers, test_data_mixed


  import time
  start = time.perf_counter()
  main()
  end = time.perf_counter()
  elapsed = end - start
  print(f'Finished in {elapsed:.02f}s')
