"""
Ensure user has all supporting TeX content to pair with Doctor.
"""

import os


class TeXDefaults:
  """
  """
  def env_table():
    return r"""
      \newenvironment{doctor-table}[5]{
        % ---------------------------------------------------------------------------
        % Flexible tabular environment based on pd.DataFrame input. Source code is 
        % beautifully typeset, alternating rows are highlighted and page breaks are 
        % handled automatically
        % 
        % Parameters
        % ----------
        % 
        % #1: Column count
        % #2: Column format
        % #3: Column headers
        % #4: Caption
        % #5: Label
        % 
        % Demo
        % ----
        % 
        % \begin{doctor-table}{4}
        %   {% Column format
        %     >{{\raggedleft\arraybackslash\hsize=\hsize}}X
        %   >{{\raggedleft\arraybackslash\hsize=\hsize}}X
        %     >{{\raggedleft\arraybackslash\hsize=\hsize}}X
        %     >{{\raggedleft\arraybackslash\hsize=\hsize}}X
        %   }{% Column headers
        %     \bfseries Numbers &
        %     \bfseries More numbers &
        %     \bfseries Text &
        %     \bfseries Mash \\
        %   }{% Caption
        %     Example table generated by Python
        %   }{% Label
        %     test
        %   }
        %   25 & 43 &       Lorem & iswdufvbouwesdbnvg \\
        %   82 & 71 &       ipsum &                abc \\
        %   23 & 52 &       dolor &            sdvcsdv \\
        %   82 & 85 &         sit &       sdvdssdvdvvn \\
        %   93 & 63 &        amet &          yumyumyum \\
        %   83 & 35 & consectetur &               wqoe \\
        %   87 & 51 &  adipiscing &            qphjpgh \\
        %   79 & 41 &        elit & owperjgpowegjwjggg \\
        %   84 & 88 &   Curabitur &        wepogjwpeog \\
        %   60 &  7 &         nec &                 oi \\
        % \end{doctor-table}
        % ---------------------------------------------------------------------------
        \small
        \rowcolors{3}{gray!5}{}
        \renewcommand{\arraystretch}{1.25}
        \xltabular{\linewidth}{#2}
        \rowcolor{white}\caption{#4}\label{table:#5} \\%
        \toprule%
        \rowcolor{white}#3%
        \specialrule{.05em}{.05em}{.05em}%
        \endfirsthead%
        
        \rowcolor{white}\caption[]{#4 (cont.)} \\%
        \rowcolor{white}\multicolumn{#1}{c}{
          \raisebox{.15em}{\resizebox{0.95\textwidth}{!}{
            \makebox[\textwidth]{\dashrule[black]}
          }}
        } \\%
        \rowcolor{white}#3%
        \specialrule{.05em}{.05em}{.05em}
        \endhead%
        
        \rowcolor{white}\multicolumn{#1}{r}{%
          \multirow{2}{*}{%
            \parbox{0.95\textwidth}{%
              \raisebox{.15em}{\resizebox{0.95\textwidth}{!}{
                \makebox[\textwidth]{\dashrule[black]}
              }}
              \raggedleft\footnotesize\textit{Continued on next page}
            }
          }
        }
        \endfoot%
        
        \bottomrule%
        \endlastfoot%
      }{
        \endxltabular
      }
    """